import type { Candidate } from "@/types/candidate";

export const candidates: Candidate[] = [
  {
    id: "maria-santos",
    name: "Maria Santos",
    professionalTitle: "Executive Virtual Assistant",
    category: "virtual_assistant",
    avatarSeed: "Maria Santos",
    professionalSummary:
      "Detail-oriented VA with 5 years supporting US and Australian founders — inbox zero, calendar management, and light bookkeeping without being asked twice.",
    location: "Cebu City, Philippines",
    yearsExperience: 5,
    skills: [
      "Google Workspace",
      "Calendar Management",
      "Email Management",
      "Notion",
      "Light Bookkeeping",
    ],
    aiSkillsTags: ["ChatGPT Workflows", "AI Meeting Notes"],
    languages: [
      { name: "English", proficiency: "fluent" },
      { name: "Filipino", proficiency: "native" },
    ],
    verified: { identity: true, email: true, phone: true },
    portfolio: [
      {
        title: "Founder Inbox System",
        description:
          "Built a triage system that cut a SaaS founder's inbox response time from 2 days to 4 hours.",
      },
      {
        title: "Quarterly OKR Tracker",
        description: "Notion dashboard used weekly by a 12-person remote team.",
      },
    ],
    workHistory: [
      {
        role: "Executive Assistant",
        client: "B2B SaaS Startup (US)",
        duration: "Jan 2023 – Present",
        description: "Manage calendar, inbox, vendor communication, and travel for a Series A founder.",
      },
      {
        role: "Virtual Assistant",
        client: "E-commerce Brand (AU)",
        duration: "Mar 2021 – Dec 2022",
        description: "Handled customer emails, order tracking, and supplier follow-ups.",
      },
    ],
    certifications: [
      { name: "Google Workspace Certified", issuer: "Google", year: 2023 },
    ],
    assessments: {
      typingSpeedWpm: 78,
      communicationScore: 94,
      skillAssessments: [
        { name: "Written English", score: 92, maxScore: 100 },
        { name: "Inbox Triage Scenario", score: 88, maxScore: 100 },
      ],
    },
    availability: "immediately",
    hoursPerWeek: "full_time",
    lastActive: "2026-07-02",
    responseRate: 98,
    responseTimeHours: 2,
    references: [
      {
        name: "Jared Cole",
        role: "Founder",
        relationship: "Former Client",
        quote: "Maria runs my calendar better than I ever did. Never dropped a single thing.",
      },
    ],
    featured: true,
  },
  {
    id: "angeline-reyes",
    name: "Angeline Reyes",
    professionalTitle: "Virtual Assistant — Real Estate",
    category: "virtual_assistant",
    avatarSeed: "Angeline Reyes",
    professionalSummary:
      "Real-estate focused VA who handles listing coordination, MLS updates, and cold-lead follow-up for US brokerages.",
    location: "Davao City, Philippines",
    yearsExperience: 3,
    skills: ["MLS", "CRM Management", "Lead Follow-up", "Canva", "Google Sheets"],
    aiSkillsTags: ["AI Listing Descriptions"],
    languages: [
      { name: "English", proficiency: "fluent" },
      { name: "Filipino", proficiency: "native" },
    ],
    verified: { identity: true, email: true, phone: false },
    portfolio: [
      {
        title: "Listing Coordination SOP",
        description: "Documented process used to onboard 2 new VAs on the same brokerage account.",
      },
    ],
    workHistory: [
      {
        role: "Transaction Coordinator VA",
        client: "Real Estate Brokerage (US)",
        duration: "Jun 2023 – Present",
        description: "Coordinates listings, updates MLS, and manages client follow-up sequences.",
      },
    ],
    certifications: [],
    assessments: {
      typingSpeedWpm: 65,
      communicationScore: 87,
      skillAssessments: [{ name: "CRM Data Entry Accuracy", score: 95, maxScore: 100 }],
    },
    availability: "within_2_weeks",
    hoursPerWeek: "full_time",
    lastActive: "2026-06-29",
    responseRate: 91,
    responseTimeHours: 5,
    references: [],
  },
  {
    id: "carlo-mendoza",
    name: "Carlo Mendoza",
    professionalTitle: "Part-Time Virtual Assistant",
    category: "virtual_assistant",
    avatarSeed: "Carlo Mendoza",
    professionalSummary:
      "Reliable part-time VA for solo founders — research, scheduling, and data entry, available evenings PH time to overlap with US mornings.",
    location: "Iloilo City, Philippines",
    yearsExperience: 2,
    skills: ["Research", "Data Entry", "Scheduling", "Google Workspace"],
    aiSkillsTags: ["ChatGPT Research Prompts"],
    languages: [{ name: "English", proficiency: "fluent" }, { name: "Filipino", proficiency: "native" }],
    verified: { identity: true, email: true, phone: false },
    portfolio: [],
    workHistory: [
      {
        role: "Freelance VA",
        client: "Multiple solo founders",
        duration: "2024 – Present",
        description: "Project-based research and admin support across 4 clients.",
      },
    ],
    certifications: [],
    assessments: {
      typingSpeedWpm: 58,
      communicationScore: 80,
      skillAssessments: [{ name: "Research Accuracy", score: 84, maxScore: 100 }],
    },
    availability: "immediately",
    hoursPerWeek: "part_time",
    lastActive: "2026-06-20",
    responseRate: 83,
    responseTimeHours: 9,
    references: [],
  },
  {
    id: "jasmine-cruz",
    name: "Jasmine Cruz",
    professionalTitle: "Senior Customer Support Specialist",
    category: "customer_support",
    avatarSeed: "Jasmine Cruz",
    professionalSummary:
      "Zendesk and Intercom expert who's handled 200+ tickets/week for DTC brands without letting CSAT drop below 95%.",
    location: "Quezon City, Philippines",
    yearsExperience: 6,
    skills: ["Zendesk", "Intercom", "Live Chat", "Email Support", "Escalation Handling"],
    aiSkillsTags: ["AI Macro Writing", "Sentiment Triage"],
    languages: [{ name: "English", proficiency: "fluent" }, { name: "Filipino", proficiency: "native" }],
    verified: { identity: true, email: true, phone: true },
    portfolio: [
      {
        title: "CSAT Recovery Playbook",
        description: "Raised a DTC brand's CSAT from 78% to 96% over one quarter.",
      },
    ],
    workHistory: [
      {
        role: "Support Team Lead",
        client: "DTC Skincare Brand (US)",
        duration: "2022 – Present",
        description: "Leads a 4-person support pod, owns escalations and macro library.",
      },
      {
        role: "Customer Support Rep",
        client: "SaaS Startup (UK)",
        duration: "2019 – 2022",
        description: "Handled live chat and email support across 3 timezones.",
      },
    ],
    certifications: [{ name: "Zendesk Support Certified", issuer: "Zendesk", year: 2022 }],
    assessments: {
      typingSpeedWpm: 82,
      communicationScore: 96,
      skillAssessments: [
        { name: "Written English", score: 95, maxScore: 100 },
        { name: "De-escalation Scenario", score: 91, maxScore: 100 },
      ],
    },
    availability: "immediately",
    hoursPerWeek: "full_time",
    lastActive: "2026-07-01",
    responseRate: 99,
    responseTimeHours: 1,
    references: [
      {
        name: "Priya Nair",
        role: "Head of CX",
        relationship: "Direct Manager",
        quote: "Jasmine is the reason our CSAT survived our biggest launch.",
      },
    ],
    featured: true,
  },
  {
    id: "ronel-delacruz",
    name: "Ronel Dela Cruz",
    professionalTitle: "Customer Support Agent — Night Shift",
    category: "customer_support",
    avatarSeed: "Ronel Dela Cruz",
    professionalSummary:
      "Night-shift specialist covering US business hours, calm under pressure with refund and billing disputes.",
    location: "Bacolod City, Philippines",
    yearsExperience: 3,
    skills: ["Live Chat", "Billing Support", "Freshdesk", "Refund Handling"],
    aiSkillsTags: ["AI Macro Writing"],
    languages: [{ name: "English", proficiency: "fluent" }, { name: "Filipino", proficiency: "native" }],
    verified: { identity: true, email: true, phone: true },
    portfolio: [],
    workHistory: [
      {
        role: "Support Agent",
        client: "Subscription Box Company (US)",
        duration: "2023 – Present",
        description: "Handles billing disputes and cancellations on the night shift.",
      },
    ],
    certifications: [],
    assessments: {
      typingSpeedWpm: 70,
      communicationScore: 89,
      skillAssessments: [{ name: "Billing Dispute Scenario", score: 86, maxScore: 100 }],
    },
    availability: "within_2_weeks",
    hoursPerWeek: "full_time",
    lastActive: "2026-06-30",
    responseRate: 94,
    responseTimeHours: 3,
    references: [],
  },
  {
    id: "patricia-lim",
    name: "Patricia Lim",
    professionalTitle: "Senior Bubble.io Developer",
    category: "bubble_developer",
    avatarSeed: "Patricia Lim",
    professionalSummary:
      "Full-stack no-code builder — ships production Bubble apps with Stripe, API integrations, and clean responsive design.",
    location: "Makati City, Philippines",
    yearsExperience: 4,
    skills: ["Bubble.io", "API Integration", "Stripe", "Responsive Design", "Airtable"],
    aiSkillsTags: ["AI Workflow Automation", "Prompt Engineering"],
    languages: [{ name: "English", proficiency: "fluent" }, { name: "Filipino", proficiency: "native" }],
    verified: { identity: true, email: true, phone: true },
    portfolio: [
      {
        title: "Marketplace MVP",
        description: "Built a two-sided marketplace on Bubble with Stripe Connect payouts, launched in 6 weeks.",
        url: "https://example.com/portfolio/marketplace-mvp",
      },
      {
        title: "Internal Ops Tool",
        description: "Replaced a client's spreadsheet workflow with a Bubble app connected to their API.",
      },
    ],
    workHistory: [
      {
        role: "No-Code Developer",
        client: "Y Combinator Startup (US)",
        duration: "2023 – Present",
        description: "Sole developer on a Bubble-based marketplace serving 3,000+ users.",
      },
      {
        role: "Bubble Developer (Contract)",
        client: "Multiple agencies",
        duration: "2021 – 2023",
        description: "Delivered 8 client MVPs across fintech, logistics, and e-commerce.",
      },
    ],
    certifications: [{ name: "Bubble.io Certified Developer", issuer: "Bubble", year: 2023 }],
    assessments: {
      communicationScore: 90,
      skillAssessments: [
        { name: "Bubble.io Portfolio Review", score: 96, maxScore: 100 },
        { name: "API Integration Scenario", score: 92, maxScore: 100 },
      ],
    },
    availability: "within_2_weeks",
    hoursPerWeek: "full_time",
    lastActive: "2026-07-01",
    responseRate: 97,
    responseTimeHours: 3,
    references: [
      {
        name: "Devon Park",
        role: "CTO",
        relationship: "Former Client",
        quote: "Patricia shipped in 6 weeks what our last agency quoted 4 months for.",
      },
    ],
    featured: true,
  },
  {
    id: "miguel-torres",
    name: "Miguel Torres",
    professionalTitle: "Bubble.io Developer",
    category: "bubble_developer",
    avatarSeed: "Miguel Torres",
    professionalSummary:
      "Early-career no-code builder, strong on UI polish and Zapier/Make automations layered on top of Bubble apps.",
    location: "Baguio City, Philippines",
    yearsExperience: 2,
    skills: ["Bubble.io", "Zapier", "Make.com", "UI Design"],
    aiSkillsTags: ["AI Workflow Automation"],
    languages: [{ name: "English", proficiency: "fluent" }, { name: "Filipino", proficiency: "native" }],
    verified: { identity: true, email: true, phone: false },
    portfolio: [
      {
        title: "Client Portal",
        description: "Bubble client portal with Make.com automations for a consulting agency.",
      },
    ],
    workHistory: [
      {
        role: "Junior No-Code Developer",
        client: "No-Code Agency (PH)",
        duration: "2024 – Present",
        description: "Builds and maintains Bubble apps for agency clients.",
      },
    ],
    certifications: [],
    assessments: {
      communicationScore: 85,
      skillAssessments: [{ name: "Bubble.io Portfolio Review", score: 80, maxScore: 100 }],
    },
    availability: "immediately",
    hoursPerWeek: "flexible",
    lastActive: "2026-06-27",
    responseRate: 89,
    responseTimeHours: 6,
    references: [],
  },
  {
    id: "ellaine-bautista",
    name: "Ellaine Bautista",
    professionalTitle: "Bubble.io + Webflow Developer",
    category: "bubble_developer",
    avatarSeed: "Ellaine Bautista",
    professionalSummary:
      "Hybrid Bubble/Webflow builder — handles marketing sites and app logic so clients don't need two hires.",
    location: "Cagayan de Oro, Philippines",
    yearsExperience: 3,
    skills: ["Bubble.io", "Webflow", "API Integration", "Figma"],
    aiSkillsTags: ["AI Copy Drafting"],
    languages: [{ name: "English", proficiency: "fluent" }, { name: "Filipino", proficiency: "native" }],
    verified: { identity: true, email: false, phone: false },
    portfolio: [
      {
        title: "SaaS Landing + App Shell",
        description: "Webflow marketing site wired to a Bubble app backend for a pre-seed startup.",
      },
    ],
    workHistory: [
      {
        role: "Freelance No-Code Developer",
        client: "Various startups",
        duration: "2022 – Present",
        description: "Delivers combined marketing site + app builds for early-stage founders.",
      },
    ],
    certifications: [],
    assessments: {
      communicationScore: 88,
      skillAssessments: [{ name: "Bubble.io Portfolio Review", score: 87, maxScore: 100 }],
    },
    availability: "not_available",
    hoursPerWeek: "full_time",
    lastActive: "2026-06-10",
    responseRate: 76,
    responseTimeHours: 14,
    references: [],
  },
  {
    id: "kristine-aquino",
    name: "Kristine Aquino",
    professionalTitle: "Brand & Social Graphic Designer",
    category: "graphic_designer",
    avatarSeed: "Kristine Aquino",
    professionalSummary:
      "Designs scroll-stopping social content and brand systems for DTC and personal-brand clients.",
    location: "Pasig City, Philippines",
    yearsExperience: 5,
    skills: ["Figma", "Adobe Illustrator", "Brand Identity", "Social Media Design", "Canva"],
    aiSkillsTags: ["Midjourney", "AI Image Editing"],
    languages: [{ name: "English", proficiency: "fluent" }, { name: "Filipino", proficiency: "native" }],
    verified: { identity: true, email: true, phone: true },
    portfolio: [
      {
        title: "DTC Rebrand",
        description: "Full brand refresh for a skincare line, including packaging mockups.",
      },
      {
        title: "90-Day Content System",
        description: "Reusable Canva template system for a coach's daily content.",
      },
    ],
    workHistory: [
      {
        role: "Brand Designer",
        client: "DTC Skincare Brand (US)",
        duration: "2022 – Present",
        description: "Owns brand identity and all social/paid ad creative.",
      },
    ],
    certifications: [],
    assessments: {
      communicationScore: 91,
      skillAssessments: [{ name: "Design Portfolio Review", score: 94, maxScore: 100 }],
    },
    availability: "immediately",
    hoursPerWeek: "full_time",
    lastActive: "2026-07-02",
    responseRate: 96,
    responseTimeHours: 2,
    references: [
      {
        name: "Sam Whitfield",
        role: "Marketing Director",
        relationship: "Former Client",
        quote: "Kristine's designs consistently outperform our agency's work, at a fraction of the cost.",
      },
    ],
    featured: true,
  },
  {
    id: "joshua-villanueva",
    name: "Joshua Villanueva",
    professionalTitle: "Presentation & Pitch Deck Designer",
    category: "graphic_designer",
    avatarSeed: "Joshua Villanueva",
    professionalSummary:
      "Turns messy founder notes into investor-ready pitch decks — clean, fast, and on-brand.",
    location: "Taguig City, Philippines",
    yearsExperience: 3,
    skills: ["PowerPoint", "Google Slides", "Figma", "Data Visualization"],
    aiSkillsTags: ["AI Slide Drafting"],
    languages: [{ name: "English", proficiency: "fluent" }, { name: "Filipino", proficiency: "native" }],
    verified: { identity: true, email: true, phone: false },
    portfolio: [
      {
        title: "Seed Round Deck",
        description: "Pitch deck used to close a $1.2M seed round.",
      },
    ],
    workHistory: [
      {
        role: "Freelance Deck Designer",
        client: "Multiple startup founders",
        duration: "2023 – Present",
        description: "Designed 20+ pitch and sales decks for early-stage founders.",
      },
    ],
    certifications: [],
    assessments: {
      communicationScore: 86,
      skillAssessments: [{ name: "Design Portfolio Review", score: 85, maxScore: 100 }],
    },
    availability: "within_month",
    hoursPerWeek: "part_time",
    lastActive: "2026-06-24",
    responseRate: 88,
    responseTimeHours: 7,
    references: [],
  },
  {
    id: "carmela-ignacio",
    name: "Carmela Ignacio",
    professionalTitle: "Certified Bookkeeper",
    category: "bookkeeper",
    avatarSeed: "Carmela Ignacio",
    professionalSummary:
      "QuickBooks-certified bookkeeper handling reconciliations, payroll support, and monthly close for US small businesses.",
    location: "Mandaluyong City, Philippines",
    yearsExperience: 7,
    skills: ["QuickBooks Online", "Xero", "Bank Reconciliation", "Payroll Support", "Financial Reporting"],
    aiSkillsTags: ["AI-assisted Categorization"],
    languages: [{ name: "English", proficiency: "fluent" }, { name: "Filipino", proficiency: "native" }],
    verified: { identity: true, email: true, phone: true },
    portfolio: [],
    workHistory: [
      {
        role: "Senior Bookkeeper",
        client: "Bookkeeping Agency (US clients)",
        duration: "2020 – Present",
        description: "Manages monthly close for 9 small-business clients across QuickBooks and Xero.",
      },
      {
        role: "Bookkeeper",
        client: "Accounting Firm (PH)",
        duration: "2017 – 2020",
        description: "Handled reconciliations and AP/AR for local SME clients.",
      },
    ],
    certifications: [
      { name: "QuickBooks Online ProAdvisor", issuer: "Intuit", year: 2021 },
      { name: "Xero Certified Advisor", issuer: "Xero", year: 2022 },
    ],
    assessments: {
      typingSpeedWpm: 60,
      communicationScore: 90,
      skillAssessments: [{ name: "Reconciliation Accuracy Test", score: 97, maxScore: 100 }],
    },
    availability: "within_2_weeks",
    hoursPerWeek: "full_time",
    lastActive: "2026-06-28",
    responseRate: 95,
    responseTimeHours: 4,
    references: [
      {
        name: "Rachel Kim",
        role: "Small Business Owner",
        relationship: "Former Client",
        quote: "Carmela caught a $4,000 reconciliation error our last bookkeeper missed for months.",
      },
    ],
    featured: true,
  },
  {
    id: "arnel-fernandez",
    name: "Arnel Fernandez",
    professionalTitle: "Part-Time Bookkeeper",
    category: "bookkeeper",
    avatarSeed: "Arnel Fernandez",
    professionalSummary:
      "Detail-driven part-time bookkeeper, ideal for small businesses that need a few hours a week, not a full-time hire.",
    location: "Antipolo City, Philippines",
    yearsExperience: 3,
    skills: ["QuickBooks Online", "Google Sheets", "Expense Tracking"],
    aiSkillsTags: [],
    languages: [{ name: "English", proficiency: "fluent" }, { name: "Filipino", proficiency: "native" }],
    verified: { identity: true, email: true, phone: false },
    portfolio: [],
    workHistory: [
      {
        role: "Freelance Bookkeeper",
        client: "Multiple small businesses",
        duration: "2023 – Present",
        description: "Handles weekly bookkeeping for 3 small e-commerce clients.",
      },
    ],
    certifications: [{ name: "QuickBooks Online ProAdvisor", issuer: "Intuit", year: 2023 }],
    assessments: {
      typingSpeedWpm: 55,
      communicationScore: 82,
      skillAssessments: [{ name: "Reconciliation Accuracy Test", score: 88, maxScore: 100 }],
    },
    availability: "immediately",
    hoursPerWeek: "part_time",
    lastActive: "2026-06-15",
    responseRate: 85,
    responseTimeHours: 8,
    references: [],
  },
  {
    id: "diane-morales",
    name: "Diane Morales",
    professionalTitle: "SDR / Outbound Sales Representative",
    category: "sales_representative",
    avatarSeed: "Diane Morales",
    professionalSummary:
      "Cold outreach specialist who's booked 400+ qualified meetings for B2B SaaS teams via email and LinkedIn.",
    location: "Muntinlupa City, Philippines",
    yearsExperience: 4,
    skills: ["Cold Outreach", "LinkedIn Sales Navigator", "HubSpot", "Email Sequencing", "Objection Handling"],
    aiSkillsTags: ["AI Sequence Writing", "Lead Scoring"],
    languages: [{ name: "English", proficiency: "fluent" }, { name: "Filipino", proficiency: "native" }],
    verified: { identity: true, email: true, phone: true },
    portfolio: [
      {
        title: "Outbound Playbook",
        description: "Built the outbound sequence that became a Series A startup's #1 pipeline source.",
      },
    ],
    workHistory: [
      {
        role: "SDR",
        client: "B2B SaaS Startup (US)",
        duration: "2022 – Present",
        description: "Owns top-of-funnel outbound, consistently hits 120% of meeting quota.",
      },
    ],
    certifications: [{ name: "HubSpot Sales Software Certified", issuer: "HubSpot", year: 2023 }],
    assessments: {
      communicationScore: 93,
      skillAssessments: [{ name: "Cold Call Roleplay", score: 90, maxScore: 100 }],
    },
    availability: "within_2_weeks",
    hoursPerWeek: "full_time",
    lastActive: "2026-07-01",
    responseRate: 97,
    responseTimeHours: 2,
    references: [
      {
        name: "Tom Reyes",
        role: "VP Sales",
        relationship: "Direct Manager",
        quote: "Diane consistently out-books reps who've been at it twice as long.",
      },
    ],
    featured: true,
  },
  {
    id: "leonard-garcia",
    name: "Leonard Garcia",
    professionalTitle: "Inside Sales Representative",
    category: "sales_representative",
    avatarSeed: "Leonard Garcia",
    professionalSummary:
      "Closes inbound demos for mid-market SaaS, comfortable running full-cycle deals from qualification to close.",
    location: "Parañaque City, Philippines",
    yearsExperience: 3,
    skills: ["Inbound Sales", "Demo Calls", "Salesforce", "Negotiation"],
    aiSkillsTags: ["AI Call Summaries"],
    languages: [{ name: "English", proficiency: "fluent" }, { name: "Filipino", proficiency: "native" }],
    verified: { identity: true, email: true, phone: true },
    portfolio: [],
    workHistory: [
      {
        role: "Account Executive",
        client: "Mid-market SaaS (US)",
        duration: "2023 – Present",
        description: "Runs full-cycle inbound deals, average close rate 28%.",
      },
    ],
    certifications: [],
    assessments: {
      communicationScore: 89,
      skillAssessments: [{ name: "Demo Call Roleplay", score: 87, maxScore: 100 }],
    },
    availability: "within_month",
    hoursPerWeek: "full_time",
    lastActive: "2026-06-22",
    responseRate: 90,
    responseTimeHours: 4,
    references: [],
  },
  {
    id: "beverly-santiago",
    name: "Beverly Santiago",
    professionalTitle: "Sales Representative — Real Estate",
    category: "sales_representative",
    avatarSeed: "Beverly Santiago",
    professionalSummary:
      "Handles inbound buyer inquiries and appointment setting for US real estate teams, strong phone presence.",
    location: "Zamboanga City, Philippines",
    yearsExperience: 2,
    skills: ["Cold Calling", "Appointment Setting", "CRM Management", "Follow-up Sequences"],
    aiSkillsTags: [],
    languages: [{ name: "English", proficiency: "fluent" }, { name: "Filipino", proficiency: "native" }],
    verified: { identity: true, email: false, phone: true },
    portfolio: [],
    workHistory: [
      {
        role: "Inside Sales Agent",
        client: "Real Estate Team (US)",
        duration: "2024 – Present",
        description: "Sets appointments for 2 buyer's agents, averages 15 booked calls/week.",
      },
    ],
    certifications: [],
    assessments: {
      communicationScore: 84,
      skillAssessments: [{ name: "Cold Call Roleplay", score: 79, maxScore: 100 }],
    },
    availability: "not_available",
    hoursPerWeek: "full_time",
    lastActive: "2026-06-05",
    responseRate: 72,
    responseTimeHours: 18,
    references: [],
  },
];
