import type { Metadata } from "next";
import { LegalPageShell } from "@/components/legal/legal-page-shell";

export const metadata: Metadata = {
  title: "Terms and Conditions — PayJobs.work",
  description:
    "Terms and Conditions governing use of the PayJobs.work AI Hiring Assistant platform, operated by PayJobs.work Manpower Services.",
};

const EFFECTIVE_DATE = "July 2, 2026";

export default function TermsPage() {
  return (
    <LegalPageShell title="Terms and Conditions" effectiveDate={EFFECTIVE_DATE}>
      <p>
        These Terms and Conditions (&ldquo;Terms&rdquo;) govern access to and
        use of the website, AI Hiring Assistant, and related services
        (collectively, the &ldquo;Service&rdquo;) provided by{" "}
        <strong>PayJobs.work Manpower Services</strong> (&ldquo;PayJobs.work,&rdquo;
        &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). By accessing
        or using the Service, you agree to be bound by these Terms. If you do
        not agree, do not use the Service.
      </p>

      <section className="flex flex-col gap-2">
        <h2>1. Description of the Service</h2>
        <p>
          PayJobs.work is a technology platform that uses artificial
          intelligence to help employers describe hiring needs, generate job
          briefs, discover and evaluate candidate profiles, and prepare for
          interviews. PayJobs.work is not itself an employer, a party to any
          employment or engagement contract formed between an employer and a
          candidate, or a guarantor of any hire, placement, or work
          arrangement. To the extent any feature of the Service constitutes
          recruitment or placement activity under Philippine law, PayJobs.work
          Manpower Services will comply with applicable requirements of the
          Department of Labor and Employment (DOLE) that apply to that
          activity.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>2. Eligibility</h2>
        <p>
          You must be at least 18 years old and capable of forming a binding
          contract under Philippine law to use the Service. By using the
          Service, you represent that you meet these requirements and that
          any information you provide is accurate.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>3. Employers and Candidates</h2>
        <p>
          &ldquo;Employer&rdquo; means any person or business using the
          Service to describe, evaluate, or fill a role. &ldquo;Candidate&rdquo;
          means any individual whose professional profile is made available
          through the Service. Employers are solely responsible for their own
          hiring decisions, for verifying any candidate&apos;s qualifications
          and eligibility to work before engaging them, and for complying
          with applicable labor, tax, and immigration law in their
          jurisdiction. Candidates are responsible for the accuracy of the
          information in their profile.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>4. AI-Generated Content</h2>
        <p>
          Job briefs, suggested salary ranges, required/preferred skills,
          interview questions, assessment recommendations, candidate match
          scores, match reasons, and AI &ldquo;fit&rdquo; summaries are
          generated by artificial intelligence based on the information you
          provide and the information available in a candidate&apos;s
          profile. This content is provided for informational purposes only,
          may be incomplete or inaccurate, and does not constitute legal, tax,
          immigration, or professional HR advice. You are responsible for
          independently reviewing and verifying any AI-generated content
          before relying on it, including before making a hiring decision or
          offering compensation.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>5. No Guarantee of Outcomes</h2>
        <p>
          We do not guarantee that any employer will find a suitable
          candidate, that any candidate will be hired, or that any match,
          score, or recommendation produced by the Service reflects a
          candidate&apos;s actual ability to perform a role. Verification
          badges shown on a candidate profile indicate only what has been
          verified and how &mdash; they are not a warranty of a
          candidate&apos;s skill, character, or performance.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>6. Fees</h2>
        <p>
          Certain features of the Service are currently offered free of
          charge. We may introduce paid or premium features in the future,
          which will be subject to additional terms and pricing disclosed to
          you before you are charged. We will not charge you without your
          consent.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>7. Prohibited Conduct</h2>
        <p>You agree not to:</p>
        <ul className="list-disc pl-5">
          <li>Submit false, misleading, or discriminatory job requirements or candidate information;</li>
          <li>Use the Service to post or seek unlawful, exploitative, or unsafe work arrangements;</li>
          <li>Attempt to circumvent rate limits, scrape the Service, or interfere with its normal operation;</li>
          <li>Use the Service to make hiring decisions based on unlawful discrimination; or</li>
          <li>Misrepresent your identity or authority to act on behalf of an employer.</li>
        </ul>
      </section>

      <section className="flex flex-col gap-2">
        <h2>8. Intellectual Property</h2>
        <p>
          The Service, including its design, branding, and underlying
          software, is owned by PayJobs.work Manpower Services or its
          licensors and is protected by applicable intellectual property
          laws. You may not copy, modify, or distribute any part of the
          Service except as necessary to use it for its intended purpose.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>9. Third-Party Services</h2>
        <p>
          The AI Hiring Assistant, candidate matching, and related features
          are powered by Anthropic&apos;s Claude models. Content you submit
          through these features is sent to Anthropic for processing. Use of
          these features is also subject to Anthropic&apos;s own terms and
          policies. We are not responsible for the availability or output of
          third-party AI providers.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>10. Privacy</h2>
        <p>
          Our collection and use of information in connection with the
          Service is described in our{" "}
          <a href="/privacy">Privacy Policy</a>, which forms part of these
          Terms.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>11. Disclaimer of Warranties</h2>
        <p>
          The Service is provided &ldquo;as is&rdquo; and &ldquo;as
          available,&rdquo; without warranties of any kind, whether express
          or implied, including warranties of merchantability, fitness for a
          particular purpose, accuracy, or non-infringement, to the fullest
          extent permitted by law.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>12. Limitation of Liability</h2>
        <p>
          To the fullest extent permitted by law, PayJobs.work Manpower
          Services will not be liable for any indirect, incidental,
          consequential, or special damages, or for any loss of profits,
          data, or business opportunity, arising from your use of the
          Service, including any hiring decision made in reliance on
          AI-generated content.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>13. Indemnification</h2>
        <p>
          You agree to indemnify and hold PayJobs.work Manpower Services
          harmless from any claim, loss, or damage arising from your use of
          the Service, your violation of these Terms, or your violation of
          any applicable law.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>14. Termination</h2>
        <p>
          We may suspend or terminate access to the Service at any time,
          with or without notice, for conduct that violates these Terms or
          that we believe is harmful to other users or the Service.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>15. Governing Law</h2>
        <p>
          These Terms are governed by the laws of the Republic of the
          Philippines, without regard to conflict-of-law principles. Any
          dispute arising from these Terms or the Service will be subject to
          the exclusive jurisdiction of the competent courts of the
          Philippines.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>16. Changes to These Terms</h2>
        <p>
          We may update these Terms from time to time. Material changes will
          be reflected by updating the effective date above. Continued use
          of the Service after changes take effect constitutes acceptance of
          the updated Terms.
        </p>
      </section>

      <section className="flex flex-col gap-2">
        <h2>17. Contact Us</h2>
        <p>
          Questions about these Terms can be sent to{" "}
          <a href="mailto:legal@payjobs.work">legal@payjobs.work</a>.
        </p>
        <p className="text-xs text-muted-foreground">
          PayJobs.work Manpower Services — [Insert registered business
          address]
        </p>
      </section>
    </LegalPageShell>
  );
}
